### ISSUE TITLE
Resuming video from where the user left 

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#12]
Should we try adding a feature where the video play resumes from where the user left last? 

Pankaj

**Comment by jhaag75** [comment]
I think this would be a nice feature. But perhaps table it for later after we've got the core stuff working?

**Comment by liveaspankaj** [comment]
will do it on the way if it's easily done when trying to pull the played segments information (i.e. last paused statement).  Because this is where will want to the user to start from.

**Comment by liveaspankaj** [comment]
Its done, will commit tomorrow after reviewing again.

**Comment by liveaspankaj** [comment]
Its done and committed. I forgot to link the commit to related tickets.
