### ISSUE TITLE
Video Profile Concepts (Verbs) Update

### ISSUE THREAD

**Issue by jhaag75** [jhaag75/xapi-videojs#13]
@liveaspankaj @jmkevan 

Opening an issue regarding the use of initialized and terminated. During out last meeting we discussed how the use of initialized and terminated are very SCORM-centric and I would prefer we use more video-centric terms such as "started" and "ended" since these are common names of events associated with video players. 

I propose we update the video profile and videoJS demo to use these verbs (started, ended) instead of initialized and terminated. I believe we discussed keeping the use of either "terminated" or "abandoned" or "exited" for scenarios where the user exited the player. I'll make the changes and issue a pull request if everyone agrees. 

If everyone agrees I'll wait until @liveaspankaj has the most recent updates pushed to the repo.

**Comment by liveaspankaj** [comment]
In video terms, I believe "ended" would relate more to reaching the end of the video, than, the user ending the session. 

Even in VideoJS "ended" event fires when the user reaches the end of the video. 

So, I am worried that we might create some confusion.

**Comment by jmkevan** [comment]
Well I think 'initialized' and 'terminated' are related to the availability of the digital asset vs interaction with it.

I would avoid 'started' b/c it sounds like a special case of 'played'. My recommendation would be 'loaded' if we want to move away from initialized.

Good point about 'ended'. Some alternatives might be 'ceased', 'discontinued' or 'finished'. I think finished and completed could be easily confused though.

**Comment by liveaspankaj** [comment]
There is another commonly used verb "attempted" which can be used for "initialized"
