### ISSUE TITLE
Using the same UUID for session-id and initialized statement id

### ISSUE THREAD

**Issue by jpablo128** [jhaag75/xapi-videojs#16]
The explanation for the context extension https://w3id.org/xapi/video/extensions/session-id (section 2.6.2.1 of https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html) states that:
    "Value of session id MUST be the UUID statement id of the initiated statement, i.e. the initialized statement."
And code in the reference implementation works accordingly.

Is there any particular reason why this 'same id' policy is needed? Wouldn't it be enough to say that the session-id has to be a UUID (with the proper format)?

Can it really be enforced at the profile definition level? In https://github.com/adlnet/xapi-authored-profiles/blob/master/video/video.jsonld   the session-id is just defined with the pattern for UUIDs... right? so the profile definition is saying that the session-id has to have that format, and must be included in "$.context.extensions".
I don't know if there's any way -in a profile definition in jsonld- to define that a given value must be equal to another value.

The issue is that if that equality cannot really be enforced and there's no specific reason for it, then the description should not use a "MUST"... (it may just suggest that you use the same id for both the video session-id and the initialized statement id... if you want...)

**Comment by jhaag75** [comment]
Good point here. We need to discuss and resolve on next group meeting.

**Comment by liveaspankaj** [comment]
We had a discussion on it in January's meeting. 

I am not familiar with the profile specification implementation and limitations so I cannot comment on it. 

However, after the discussion on the call, it was agreed that making the session id same as uuid simplifies the implementation to remove one extra thing to worry about (for the implementers). 

Making it a MUST doesn't technically cause any problems or limitation and hence we did not find any reason to change it in the video profile.
