### ISSUE TITLE
Use of last 'paused' statement as a source of state

### ISSUE THREAD

**Issue by jpablo128** [jhaag75/xapi-videojs#17]
The current implementation reads the latest 'paused' statement for the currect activityID and agent (and registration if present) to obtain the latest played-segments, currentTime, and 'completed' information.

This is basically state information (progress of the user on the activity),  so it could be saved/retrieved using the State API. So I'm curious about why you don't use the State API for this. I guess that since this info is already there in latest 'paused' statement, you just retrieve it, instead of saving/loading a separate document... so, in a way I understand ... but I have 2 thoughts about why I would have used the State API for this:

1. I normally don't (or wouldn't) assume that because an LRP has the capability/permissions to PUT or POST statements, it also has permissions to GET statements. I know that normally, in general, write permission implies read permission (in fact, in LearningLocker their code works on that premise) ... but in xAPI, I think it may make sense -in some situations- to allow writes and deny reads. Of course you could argue that an LRP might be denied access to the State API as well...

2. Now it's only 3 pieces of info (played-segments, currentTime, and 'completed'), but if you wanted to save more state information (such as full-screnn vs. non-full screen, playback rate, subtitle active/inactive and subtitle language, etc.) ... then the 'paused' statement doesn't have that info (and you wouldn't want to put it in every 'paused' statement). It would be trivial to save more information like that if the State API was used.⋅

Also, using the state API it would be possible to 'reset' the state of a user on a video just by deleting the corresponding state API document (although I'm not sure if that's a very necessary feature).

**Comment by jhaag75** [comment]
Good point. Any thoughts on this @liveaspankaj ?

**Comment by liveaspankaj** [comment]
The ideas make sense, but as discussed on the call. It would mean storing the same information via State API as available in paused statement. 

Yes, if there are other information that needs to be stored, and if it is not available easily from the statements, it can be stored using the State API. 

It is more of a implementation decision, and not a profile related issue.
