### ISSUE TITLE
Quality / YouTube Quality for VideoJS Demo

### ISSUE THREAD

**Issue by jhaag75** [jhaag75/xapi-videojs#18]
I recommend we remove the "quality" context extension from the VideoJS demo. It doesn't seem to make sense to force this extension for a few reasons:

- This is a property typically associated with youtube terminology. The video CoP adopted it from the YouTube player actually, but VideoJS does not have a control that allows the user to change the quality. Since this isn't a setting in the VideoJS player, I recommend we remove it from this demo/example.

- It's an optional setting on the video youtube player, that only is provided for videos with high resolution that allow for adaptive alternatives.

- On line 198 in the xapi-video.js, the function to get the video width (videoWidth() ) is not returning the actual quality settings that align with the youtube player.

BTW, I started to look at this resource: https://github.com/videojs/videojs-youtube

It combines VideoJS with a remotely hosted YouTube video. When I combine it with our example, it throws an error on the videoWidth function and says it is not defined. Therefore, it never sends the send_initialized() function. Otherwise, it seems to work really well with our VideoJS demo.

**Comment by liveaspankaj** [comment]
Hi Jason,

Thanks for pointing that out. 

Can we make it such that we use it when it is available? 

Also does VideoJS allow us to read the YouTube video's quality setting directly or indirectly? 

Do you have a test implementation for YouTube that I can take a look?

Pankaj

**Comment by jhaag75** [comment]
Yes, I'll push what I have so far.
