### ISSUE TITLE
Move demo actor configuration to index.html. Allow LRS and actor configuration to be used from launch url 

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#2]

**Comment by jhaag75** [comment]
Thanks for doing this. Also, for actor configuration what do you guys think about using something like hello.js?

https://adodson.com/hello.js/demos/profile.html

This provides a social login capability so we can dynamically set the actor name and email based on the user's google, facebook, twitter, or windows account.

**Comment by liveaspankaj** [comment]
+1
