### ISSUE TITLE
Question on using sessiodID for initialized and difference between `registration` and `sessionID` for context

### ISSUE THREAD

**Issue by ghost** [jhaag75/xapi-videojs#21]
Could someone explain the use of the session ID for the id of the initialized statement? https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L217
For the other statements, no id is assigned, therefore I'm assuming that is intentional, so the LRS would assign the UUID.
Is there a specific reason why the initialized statement gets an explicit assignment? Concurrently, the `sessionID` is reused within the context property, which seems to relate each of the different statements to one experience. But the `registration` property seems to do the same. What is the functional difference between the two?

**Comment by liveaspankaj** [comment]
All statements in a session should have same sessionID.

Using the statement.id on the initialized statement  is just to give one
less thing to worry about for the developer.

sessionID tells that all these statements came from one session or one
sitting or one attempt whatever you want to call it.

registration property tells that all the statements with same registration
happened for one registration or enrolment.

So, if same registration is used and you attempt same video even if after
several days or months, you will notice few things:
1. The video starts from where you left last time.
2. The video is marked as completed, even if you consume the rest of the
video that you did not consume earlier.
3. All played segments for all attempts for same registration will be
reported together in paused or completed statements.

Let me know if that makes sense.

Regards,
Pankaj Agrawal

**Comment by ghost** [comment]
Thanks very much for the explanation, @liveaspankaj. It makes more sense to me now. But I'm not clear whether using the session ID as the initial id for a series of related statements is something you had defined on your own, or it's something standardized in the spec. I reviewed the spec but couldn't find anything specific. It seems like what is implemented is generic enough to apply for other sequential learning use cases. Can I find more reference about that, or could you discuss the decisions you made that lead to that?

From your description of the `played_segments`, I now see the level which you are saving application state using xapi statements, which I have further questions about and will open a new issue to ask. Thanks!

**Comment by liveaspankaj** [comment]
@garajo  We are not using session ID as the statement id, but its the other way round. We are using statement id of the first statement in the series of statements as the session ID of all these statements in that series/session. 

session ID is not a new concept, it is also used in cmi5. 

Using statement id of initialized statement is a unique concept in the Video Profile, though anyone can use it in any profile. It helps in few ways: 
1) Developers don't need to worry or guess what it should be. 
2) Developers will not make it a fixed UUID value to avoid generating a random UUID. 
3) Developers will not used any other format for the session ID value


 

https://github.com/jhaag75/xapi-videojs/issues/17

**Comment by ghost** [comment]
Yes, I'm familiar with session ID. You answered my question with, 'Using statement id of initialized statement is a unique concept in the Video Profile'. 

~~So, the construct of using https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L217 , further propagating and relating statements under the context.extensions property is one that you had defined, and not specified in the official specification, is that right?~~ See below

**Comment by ghost** [comment]
This example repo uses registration as a static constant that is [predefined](https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L11) to represent, ['one registration or enrolment'](https://github.com/jhaag75/xapi-videojs/issues/21#issuecomment-393831583)

To clarify, I read the spec some more, and it seems there is some room for interpretation for the `registration` property. 

_"A registration could be considered to be an attempt, a session, or could span multiple Activities. There is no expectation that completing an Activity ends a registration. Nor is a registration necessarily confined to a single Agent."_   [ref](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2461-registration-property). 

So, I am interpreting this to mean the `registration` property can be used in different ways for codifying associations across statements.

**Comment by liveaspankaj** [comment]
@garajo 

The "registration" property in Video Profile works in line with how it is explained in the xAPI Spec. 

If you use same registration value across attempts or sessions for the video, the progress and segments will be carried over, and completion will be calculated based on all the past attempt with same registration value for that video/activity. 

If same registration value is used across multiple users and multiple activities (videos). It would technically work same as explained above. 

If you want the video to start over in every attempt, and not use any past progress from the user, then you can simply use a random registration UUID on every attempt.

**Comment by ghost** [comment]
Thanks for @liveaspankaj for clearing this up!
