### ISSUE TITLE
Question about State and the differences between Result.extensions, context.extensions, State Resource

### ISSUE THREAD

**Issue by ghost** [jhaag75/xapi-videojs#22]
Some states are in `context.extensions`,  https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L238-L255

Others are in `result.extensions`, or a combination of both, https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L396-L409

I've reviewed it several times, but I don't understand what differentiates one to the other. Could someone explain please?

In addition the spec denotes a **State Resource** as a 'a scratch area for Learning Record Providers that do not have their own internal storage, or need to persist state across devices'
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#stateres
How does that fit in with the other two?

So this leads me to believe that we can omit state from the statements altogether, if the session state is not pertinent to the objectives on hand. Am I correct in assuming that if I were to build my own video profile implementation, it would be okay to leave out `context.extensions` and `result.extension`? Would there be any reporting requirements or vantages I'd be missing out, that I I'm not seeing at the moment?

**Comment by liveaspankaj** [comment]
Extensions that determine the result or outcome of the activity is part of Result Extension. 

Extensions related to the context of the activity are part of the Context Extensions. 

State Resource is "a scratch pad area" for information of temporary significance.

Context Extension gives important information about the context or environment in which the activity took place. 
For example, volume  = 0 means mute. So, any video being watched with volume = 0, means the user was not listening to the audio. 
or, video-playback-size = 1x1 would mean the video playback size was reduced to a size such that it could not be watched. So, probably the user was only listening to the video. 

Result Extension, gives important outcome related information. 
For example, played-segments gives details of what parts of the video has been watched by the user. played-segments also makes it possible to calculate the completion % (progress) of the video. 
Similarly "time" in a played or paused statement gives accurate information about where the video was started or paused. 

All required extensions need to be provided. All optional extensions can be omitted but some of them might be very useful.

**Comment by ghost** [comment]
Thanks for your thoughts, @liveaspankaj . I have follow up questions please.

The result in this statement is *time*; https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L324
This statement is triggered when a change to the closed captioning occurs, https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L273

It seems odd that the result would be *time*, since the pertinent variable seems to be whether closed captioning is available. https://github.com/jhaag75/xapi-videojs/blob/master/xapi-videojs.js#L336 .   Can you clarify how *time* is a 'result'? It seems that time in all the statements here is the standard result type. Is that correct? How is it a "result" for all?

You said, "All required extensions need to be provided.". Where can I find what is 'required'? It seems to me all the extensions are optional, depending on the data of the statements you look to collect. Can I get a spec on that?

I'm not ready to follow the assumption that if the volume is 0 or screensize is too small, that the user is not learning. For example, what about for blind and deaf people? Furthermore, I haven't seen learning analysis and validations codified anywhere in the specs. Nor do I believe that it should be, but that's not what I'm asking. Is there such spec as 'volume = 0, means the user was not listening to the audio'? If so, kindly please share a link, and teach me an example how to use it.  But what I really want to know is whether there are indeed requirements for these properties and for what reasons would they be required. Thank you

**Comment by liveaspankaj** [comment]
@garajo 
If you have not already gone through, the Video Profile document should explain several of your questions: 
https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html

Regarding your question on what should go into Result Extension and what should go into Context Extension, it is a confusing topic and can be discussed and debated. 

Our interpretation from the xAPI Spec, is that anything that defines the environment in which the activity is happening should go into the Context Extension. And anything the user is doing or that decides the outcome/result is part of the Result Extension. 

For Required/Optional, and other requirements, you can see the document above. 

For the volume, it needs to be between 0 and 1 and tells the volume percentage, where volume = 0 means Mute, and volume = 1 means full volume. So, if volume = 0, we know that the video is mute and the user is not listening to the audio. If the volume = 1, we can assume that the user is listening, however, he might be deaf, or not listening, or playing golf outside, Video Profile doesn't guarantee user is listening or learning. We can only make assumptions based on what the player reports.

Again, if you look at the above document, it should remove a lot of confusions.

**Comment by ghost** [comment]
I think I see now how required extensions are denoted. @liveaspankaj , is the `length` extension required because its LRP Obligations field says, '_It MUST be included in Video Profile_ statements with these verbs' . For example, is `length` the only property that is required, and only if the statements verbs are _initialized, completed, terminated or paused_. Is that right?


Would you be open to a PR to try to table these properties into a more condensed and obvious view?

**Comment by liveaspankaj** [comment]
@garajo 

There are several extensions which are required but depends on the verbs or other conditions. 

I agree there is scope for improvements, and there might be inconsistencies. I am open to any suggestions or PR. 

Probably listing all required extensions in each verb, might help? 

Really appreciate your efforts. 

Pankaj

**Comment by ghost** [comment]
@liveaspankaj I signed up with Gitbook and then tried to access the docs repo, but strange things are happening. It seems like Gitbook has a new version and a legacy version in production. For some reason it won't allow me to access the docs Gitbook site because it's in the legacy version, and I can only sign up using the new version. Do you know anything about this? Thanks

**Comment by liveaspankaj** [comment]
@garajo No idea, but are not not able to use "Sign In with GitHub" from this url: https://legacy.gitbook.com/login

**Comment by ghost** [comment]
Not able, this is what I get trying to do that. Someone forgot their UAT...

![screenshot from 2018-06-05 11-12-01](https://user-images.githubusercontent.com/2825366/40994554-62957750-68b1-11e8-8b4e-711eaffee3bd.png)

**Comment by liveaspankaj** [comment]
What if you create the account from new version, and then login to legacy?

**Comment by ghost** [comment]
I tried that too. No luck. I couldn't even find where to write their
support. They seem to have only self-help support

**Comment by liveaspankaj** [comment]
Maybe send a PR on github?
https://github.com/liveaspankaj/xapi-video-cop/blob/master/statement_data_model.md

It will update the gitbook automatically, because gitbook uses the github repo. 

Pankaj

**Comment by ghost** [comment]
that it, thanks!
