### ISSUE TITLE
Is forcing a registration value required

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#23]
https://github.com/jhaag75/xapi-videojs/blob/0ee6e0be8c8a25b5292d3bb9a786cebbf1c5c86c/xapi-videojs.js#L112

It seems a random registration value is being forced here. Is it required. 

Also if a registration value is not there, why do we need to add a registration value? 

Pankaj

**Comment by liveaspankaj** [comment]
@jhaag75

**Comment by jhaag75** [comment]
I'm not sure. I thought that it was checking the ADL Wrapper for a registration first, and then if it didn't get one from there to generate one using var registration = ADL.ruuid();

**Comment by liveaspankaj** [comment]
It looks like it is checking, but still changing the registration value. 

But, even if registration value is not available, adding a random registration will be useful when you do not want the user to be able to resume the progress and viewing from where he left.

Pankaj

**Comment by liveaspankaj** [comment]
This issue is fixed
