### ISSUE TITLE
Replace console.log(...) by ADL.XAPIWrapper.log(...) ?

### ISSUE THREAD

**Issue by sfraysse** [jhaag75/xapi-videojs#25]
Hi,
There are a few `console.log(...)` hardcoded in the `xapi-videojs.js` file.
This could be replaced by `ADL.XAPIWrapper.log(...)` in order to let people deactivate logs with `ADL.XAPIWrapper.log.debug = false;`.

**Comment by jhaag75** [comment]
That's a good suggestion. If you want to make a commit we'll review and merge it.
