### ISSUE TITLE
Several changes

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#3]
1. Change time value from string to float with max 3 decimal places. 
2. Change volume in initialized verb from percentage to float with max 3 decimal places.  
3. Fix time-from is always null. 
4. Change time-to and time-from to float with max 3 decimal places. 
5. Use session id uuid as statement id of initialized statement. 
6. Change speed extension value from 1 to "1x"

**Comment by jhaag75** [comment]
Thank you for finding these Pankaj. Nice work!
