### ISSUE TITLE
two issue with seeked 

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#4]
I see there are two issues with seeked. 

1. When I seek, it sends a paused verb before seeked and a play verb after seeked. This makes seeked as a redundant statement. Ideally it should be sending only seeked statement. 

2. When I seek by dragging the bar instead of clicking on another point of time. Then it sends several seeked statements instead of one. (https://screencast.com/t/g0A2oB2gc ) 

What is the best way to solve these issues? 

PS: On one call, we did discuss if we should drop the seeked verb and should use paused and played instead to represent same thing. However, few people prefered having seeked verb.

**Comment by jmkevan** [comment]
Yea, I personally think seeking.. and play/pause represent different actions. 

1) I don't see a problem with only sending the seeked statement out. You could always count it as a play/pause if you needed to, but not sure what that use case would be.

2) Send statement on mouseup?

Those are my suggestions. Will try and look at it this weekend.

- J

**Comment by jhaag75** [comment]
It sends a paused and played statement though based on the "pause" and "play" event handler interactions in VideoJS. When the seek bar is initially clicked it triggers a pause event and when it is released it triggers a play event. I don't think we can prevent this unless we change the VideoJS library, can we?

Only the seeked statement appears to be actually sending the "time from" and "time to" values. I don't think there's any problem with this actually. The pause and played statements are being sent as they should be. It's actually a good indicator that seeked was triggered correctly.

I don't see this as a problem honestly. How is it a problem?

**Comment by liveaspankaj** [comment]
The current Video Profile tells the LAP to send one seeked verb when a user seeks to another point in video. And that seeked verb tells the from and to time in video where the user seeked. However, what is happening here is: We get three statements. a. Paused (at the "time-from" point in video). b. A seeked verb (as expected) c. A play verb (at the "time-to" point in video) 

So, this causes two extra statements that are not required by the profile. And, believe me extra statements are a pain in the LRS storage. 

Additionally, it would cause unexpected behaviour assumption by a reporting tool that follows Video Profile. It would say something that would interpret like:
1. User click "Paused"
2. User "Seeked" to another point in video.
3. User click "Play" 

So, as we are building a prototype for Video Profile, we should find a way to fix this, or we should adjust the Video Profile support this.

If VideoJS generates these extra events of paused/played when a user seeked, it may or may not be easy to identify what caused the event based on what information is provided by VideoJS. 

Apart from extra paused/played statements. The multiple seeked statements are a problem. 
I like Jon's suggestion of using mouseup, however, I am not sure if we can use two events i.e. VideoJS's seeked event and mouseup event to trigger one seeked statement. 

But, there should be some way to figure that out.

**Comment by jmkevan** [comment]
For issue 1, it seems like the easiest solution is to just avoid sending the pause and play xAPI statements to the LRS.

Sending a pull request for this adjustment now. Please feel free to review, not a coder by trade :-).

**Comment by jhaag75** [comment]
So I tested this out. @jmkevan 's update resolved the issue #1 that Pankaj identifed. However, it appears that issue #2 is still something we need to look at. 

" 2)When I seek by dragging the bar instead of clicking on another point of time. Then it sends several seeked statements instead of one. (https://screencast.com/t/g0A2oB2gc )"

I think we need to find a way to only send the seeked verb when the mouse down event is released. I'm not sure if it's the same event for mobile devices. Need to look at the documentation to see if that's possible. Currently it is sending the seek statement when every you drag the timeline from one point to another. It's real noisy and not what we want.

**Comment by jmkevan** [comment]
Was able to poke around this a bit, but can't spend any more time on it today.

Attempted to use myPlayer.scrubbing() to get if the user is actively scrubbing as a logic operator, but it appears this event is always true during the myPlayer.on('seeked', function) event.
http://docs.videojs.com/Player.html#scrubbing

I then tried accessing the seekBar directly:
http://docs.videojs.com/SeekBar.html

I did some poking around and the mouseup event appears to trigger accurately in every test I performed: 
`myPlayer.controlBar.progressControl.seekBar.on("mouseup", function(){
//console.log(myPlayer.controlBar.progressControl.seekBar);
console.log('mouse went up');
});`

Currently, my recommendation is to move items from the scrubbed event to the seekBar mouseup instead. I haven't had a chance to look at or try this on mobile yet. I will poke around with it next weekend, but figured I would share my findings in case someone else gets to it.

- Jon

**Comment by liveaspankaj** [comment]
Thanks Jon, 

Your code helped. I have committed a modification that fixes the multiple seeking statements. 

Essentially I am asking it to send the seeked statement when it was sending the "played" statement at the end of the seeking period. 

Let me know if it looks good.

**Comment by jhaag75** [comment]
Looks good! Merged.
