### ISSUE TITLE
interacted full screen showing video playback size same as without full screen. 

### ISSUE THREAD

**Issue by liveaspankaj** [jhaag75/xapi-videojs#8]
interacted full screen showing video playback size same as without full screen. 

Full Screen: https://screencast.com/t/eblaERUT
Normal: https://screencast.com/t/I5xZDc6isP

**Comment by jhaag75** [comment]
I see what you mean. What would you guys like to update it to? 

The video playback size is the intended playback size, which is set by the Video JS player controls. Do you want this to be dynamic and updated to the current size of the screen? That's the same thing as screen size if fullscreen = true. 

Seems kind of redundant. Another option is to not set the video-playback-size extension if fullscreen is true. That way you know the size of the video is the size of the current screen size.

**Comment by liveaspankaj** [comment]
technically screen-size and video-playback-size can be different even in fullscreen. 

screen-size is expected to be total screen size (known to the player)
video-playback-size is the the size taken by video. now in some cases I see that even in full screen mode the video can be limited to say browser size. 

so, if the player knows the real size of screen, but on full screen it can only size the player to the browser size, we will have different sizes for the two. 

it is possible that vimeo might have both values same in full screen mode. though I have not confirmed.

**Comment by liveaspankaj** [comment]
I was able to fix the video-playback-size to correct value by using: myPlayer.currentWidth() and myPlayer.currentHeight() instead of myPlayer.width() and myPlayer.height()

I tried adding quality value to the initialized statement, but it seems the value is available only after play button is clicked. I was trying to use this line of code:

var quality = (myPlayer.videoHeight() < myPlayer.videoWidth())? myPlayer.videoHeight():videoWidth();

should we sent initialized statement after play button is clicked? there is a key advantage in doing so. whenever a video is displayed in a page for users to watch. you would not want see the initialize statement only after the player starts it. otherwise, if there are 50 videos on the page, we will have 50 statements in the LRS where as even a single video session practically did not start at all. 

Pankaj

**Comment by jmkevan** [comment]
I agree with your thinking on this Pankaj. It's not particularly useful 
to know 50 videos loaded, but were not 'experienced'. The lack of play 
statements tells the same story with less data.

We have done similar delayed statement sending when tracking assessment 
data. As long as the 'timestamp' of the event is accurate, when it gets 
'stored' is irrelevant.

- J

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu


------ Original Message ------

**Comment by liveaspankaj** [comment]
@jmkevan thanks for confirming. 

For the records on this ticket. It was decided in today's meeting that we will change and send the initialized statement when the video starts. 

Regarding your point of timestamp. I agree that it doesn't matter if the statement sending is delayed as long as timestamp is accurate. 

However, for this specific issue of initialized verb. I believe that the timestamp for initialized should be when the video starts and not when the page was loaded in browser (that is approximately when the ready event is currently generated and initialized statement is sent). I do not think that as part of video profile we should worry about anything before the video consumption starts, unless there is real value in that information. If required, we can make the description of initialized verb in Video Profile a little more descriptive. 

Pankaj

**Comment by jhaag75** [comment]
Following up on this so I can take action. So rather than sending an initialized statement when the video is played. Why don't we just send this initial player information when the played statement is sent? Does that work?

**Comment by liveaspankaj** [comment]
Do you mean remove the "initialized" verb completely? we cannot do that because there will be no good way to identify when the session started. 

 I will probably take care of this part as I am already playing around related code. Will let you know if I don't do it.

**Comment by liveaspankaj** [comment]
Its done, will commit tomorrow after reviewing again.

Also added the quality extension.

**Comment by liveaspankaj** [comment]
Its done and committed. I forgot to link the commit to related tickets.
